version: 2.1
description: Automatically build and push to your GitHub Repo Wiki

jobs:
  build:
    docker:
      - image: circleci/node
    steps:
      - checkout
      - run:
          name: Push Wiki To Project Wiki
          command: |
            git config user.email "${GITHUB_EMAIL}"
            git config user.name "${GITHUB_USERNAME}"
            git remote remove origin
            git remote add origin https://${GITHUB_API_KEY}@github.com/gommzystudio/lymmzy_wiki > /dev/null 2>&1
            git push origin master > /dev/null 2>&1

workflows:
  main:
    jobs:
      - build:
          filters:
            branches:
              only: master
